version: "3.7"
services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    container_name: board-mysql_8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=board
      - MYSQL_ROOT_PASSWORD=board
      - TZ=Asia/Seoul
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - ./data_8:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)